/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as InvestigationsThreadIdRouteImport } from './routes/investigations/$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsThreadIdRoute = InvestigationsThreadIdRouteImport.update({
  id: '/investigations/$threadId',
  path: '/investigations/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/investigations/$threadId': typeof InvestigationsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/investigations/$threadId': typeof InvestigationsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/investigations/$threadId': typeof InvestigationsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/investigations/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/investigations/$threadId'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/investigations/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiMeRoute: typeof ApiMeRoute
  InvestigationsThreadIdRoute: typeof InvestigationsThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$threadId': {
      id: '/investigations/$threadId'
      path: '/investigations/$threadId'
      fullPath: '/investigations/$threadId'
      preLoaderRoute: typeof InvestigationsThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiMeRoute: ApiMeRoute,
  InvestigationsThreadIdRoute: InvestigationsThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
