CREATE SCHEMA IF NOT EXISTS fhi_chat;

CREATE TABLE IF NOT EXISTS fhi_chat.chat_sessions (
    session_id TEXT PRIMARY KEY,
    dsn_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_active TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fhi_chat.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL
        REFERENCES fhi_chat.chat_sessions (session_id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    queries_used JSONB NOT NULL DEFAULT '[]'::jsonb,
    raw_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS chat_messages_session_id_id_idx
    ON fhi_chat.chat_messages (session_id, id);

CREATE INDEX IF NOT EXISTS chat_sessions_last_active_idx
    ON fhi_chat.chat_sessions (last_active DESC);

SELECT format('GRANT USAGE ON SCHEMA fhi_chat TO %I', :'app_role') \gexec
SELECT format(
    'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA fhi_chat TO %I',
    :'app_role'
) \gexec
SELECT format(
    'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA fhi_chat TO %I',
    :'app_role'
) \gexec
SELECT format(
    'ALTER DEFAULT PRIVILEGES IN SCHEMA fhi_chat GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I',
    :'app_role'
) \gexec
SELECT format(
    'ALTER DEFAULT PRIVILEGES IN SCHEMA fhi_chat GRANT USAGE, SELECT ON SEQUENCES TO %I',
    :'app_role'
) \gexecI